"""empty message

Revision ID: 13db7f370211
Revises: 
Create Date: 2025-12-12 16:51:11.134801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13db7f370211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availablity',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('appointment',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.uid'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('availablity')
    # ### end Alembic commands ###
