"""empty message

Revision ID: a5a576aa5900
Revises: 13db7f370211
Create Date: 2025-12-12 17:07:18.193825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a576aa5900'
down_revision = '13db7f370211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('availablity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availablity',
    sa.Column('uid', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('availability')
    # ### end Alembic commands ###
